import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers as RTKProviders} from "@/redux/provider";
import React, {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <RTKProviders>{children}</RTKProviders>
        </body>
        </html>
    )
}
